variable "group" {}
variable "project" {}
variable "env" {}
variable "vpc_cidr" {}
variable "enable_dns_hostnames" {}
variable "enable_dns_support" {}
variable "azs" {}
variable "public_subnets" {}
variable "private_subnets" {}
variable "map_public_ip_on_launch" {}